fix: change the explorer link for bitcoin
lifinance/data-types pull request #77
Opened 2024-11-04 09:44 UTC by myz1237

2024-11-05 13:15 UTC, myz1237 commented
This one is for https://github.com/lifinance/lifi-backend/pull/5738

2025-01-13 15:14 UTC, chybisov requested changes
@myz1237 I intentionally changed it `mempool` to be the first block explorer for Bitcoin because it is better and widely used in the ecosystem. Why did we decided to change it back?

2025-01-22 07:34 UTC, myz1237 commented
@chybisov that's how we generate bitcoin explorer in our backend: 
<img width="876" alt="image" src="https://github.com/user-attachments/assets/f16f4fa4-261f-4fa1-80c0-72f2da67cb8f" />
I wanna unify it to use `chain.metamask.blockExplorerUrls[0] + 'tx/' + txHash`

2025-01-22 09:54 UTC, chybisov commented
> @chybisov that's how we generate bitcoin explorer in our backend: <img alt="image" width="876" src="https://private-user-images.githubusercontent.com/54893307/405517028-f16f4fa4-261f-4fa1-80c0-72f2da67cb8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1Mzk4MDUsIm5iZiI6MTczNzUzOTUwNSwicGF0aCI6Ii81NDg5MzMwNy80MDU1MTcwMjgtZjE2ZjRmYTQtMjYxZi00ZmExLTgwYzAtNzJmMmRhNjdjYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDA5NTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MWEzY2JhYjdkNTE1ZjYyMGQ4MGYwZTk0NzgyYTQ4ZTAyMmYyOGEzODQ2OWYzMzE5OThlYWJlNTdlNDI2MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rI4sdArdFhlJXJEUExS6XxRRbwhVB2vmNf025JsXbjs"> I wanna unify it to use `chain.metamask.blockExplorerUrls[0] + 'tx/' + txHash`

Both blockchair and mempool support this format:

https://mempool.space/tx/7898d4a8e9cc98a3318873bd3fd1ce731de63cdadf9d85868ac65bcf7d4effcc
https://blockchair.com/bitcoin/tx/7898d4a8e9cc98a3318873bd3fd1ce731de63cdadf9d85868ac65bcf7d4effcc

2025-03-18 13:53 UTC, closed without merging